### ISSUE TITLE
some new features

### ISSUE THREAD

**Issue by mg979** [kronos-io/kronos.vim#6]
I added some features in [my fork](https://github.com/mg979/kronos.vim). I can make a PR if you're interested, but I didn't set up tests for the note feature (old tests are still successful).

**Change where Kronos is opened**:
- by default Kronos is opened in a new tab, when closing you are brought to the old tab
- you can set `g:kronos_wincmd` to `vs`, `sp`, `tabedit`, etc to change this behaviour

I made this change because `bdelete` closes the window where you opened Kronos, and if you had a split, it will be gone. Now, if you open it in a split (`vs`), a new split is created and the Kronos window size is automatically readjusted.

**Add a note to a task**:
- by pressing `n` in the gui (either in list or info view), you open a new `Note` pane
- the note is automatically saved when pressing Esc, but only stored if not empty (must match a `\w`)
- `dn` deletes the note if pressed in the `Note` or in the `Info` pane (not in the `List`)

![Imgur](https://i.imgur.com/YDsTyuh.gif)

**Comment by soywod** [comment]
Thank you so much for your contribution ! I will try your work and let you know. It looks interesting. The only things is I'm refactoring a bit everything to match better the [protocol](https://github.com/kronos-io/kronos) I wrote (to be more coherent with all clients). So if such a feature will be added, it's gonna be after the refactor, and I will also have to update the protocol.

I'm curious, since when do you use this plugin ? And which tool you use to have the key pressed appearing on the screen while recording ?

**Comment by mg979** [comment]
> I'm refactoring a bit everything

Since you're refactoring, you could have care to change these [helper functions](https://github.com/kronos-io/kronos.vim/blob/0ef494abb2983dd29263d13d02e28235a2bf421f/autoload/kronos/gui.vim#L272) names, because after the file is sourced they can be called as commands and included in vim command line completion.

> I'm curious, since when do you use this plugin ? And which tool you use to have the key pressed appearing on the screen while recording ?

The program is [ScreenToGif](https://www.screentogif.com/). I've been using the plugin for a few days (like I did that fork on day 1). Very cool btw, I like that you are sticking to the essentials, it's very easy to use.

**Comment by soywod** [comment]
> Since you're refactoring, you could have care to change these helper functions names, because after the file is sourced they can be called as commands and included in vim command line completion.

Yes it's already the case :) I turned them into script functions with `s:` to avoid this.

> The program is ScreenToGif.

Thanks, I will have a look!

> Very cool btw, I like that you are sticking to the essentials, it's very easy to use.

I'm glad you like, indeed I want this tool to be as simple as possible, and not to fall into a TaskWarrior (which is over-complicated in my opinion).

**Comment by mg979** [comment]
> TaskWarrior (which is over-complicated in my opinion)

Yes I agree, I'd rather use a simple todo file than that kind of apps.

**Comment by soywod** [comment]
The main new feature that will come with the refactor is the realtime sync between devices, so theoretically, you could have a realtime sync tasks between your web app, mobile app or vim plugin: https://www.reddit.com/r/vim/comments/9hhz0r/task_time_manager_synchronised_between_devices

**Comment by mg979** [comment]
I'll mostly use it in vim, but it sounds cool.

**Comment by soywod** [comment]
I just pushed the refactor. Code structure is simplified, code convention has changed (snake case everywhere), and I plugged the sync system (the aim was to normalise things, following the [Kronos protocol](https://github.com/kronos-io/kronos)). So you will have to modify a bit your code. But once you ready, you can propose your PR :)
